services:
  - type: web
    name: acadweb-app
    runtime: python
    buildCommand: |
      npm install && \
      npm run build && \
      pip install -r backend/requirements.txt
    startCommand: "python backend/main.py"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_API_BASE_URL
        value: "https://acad-d1mk.onrender.com"
